-- MySQL Script generated by MySQL Workbench
-- Sat Jun 12 13:38:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema manics
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema manics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `manics` DEFAULT CHARACTER SET utf8 ;
USE `manics` ;

-- -----------------------------------------------------
-- Table `manics`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manics`.`usuarios` (
  `user_id` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manics`.`sugerencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manics`.`sugerencias` (
  `sugerencia_id` INT NOT NULL,
  `user_id` INT NULL,
  `contenido` VARCHAR(45) NULL,
  `fecha_creacion` VARCHAR(45) NULL,
  PRIMARY KEY (`sugerencia_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_sugerencia_usuario`
    FOREIGN KEY (`user_id`)
    REFERENCES `manics`.`usuarios` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manics`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manics`.`categorias` (
  `categoria_id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manics`.`comics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manics`.`comics` (
  `comic_id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NULL,
  `anio_publicacion` INT NULL,
  `capitulos_disponibles` INT NULL,
  `categoria_id` INT NULL,
  PRIMARY KEY (`comic_id`),
  INDEX `fk_categoria_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_comic`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `manics`.`categorias` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manics`.`comentarios_comics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manics`.`comentarios_comics` (
  `comentario_id` INT NOT NULL,
  `user_id` INT NULL,
  `comic_id` INT NULL,
  `contenido` VARCHAR(45) NULL,
  `fecha_creacion` VARCHAR(45) NULL,
  PRIMARY KEY (`comentario_id`),
  INDEX `fk_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_comic_idx` (`comic_id` ASC) VISIBLE,
  CONSTRAINT `fk_comentario_user_comic`
    FOREIGN KEY (`user_id`)
    REFERENCES `manics`.`usuarios` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_comic`
    FOREIGN KEY (`comic_id`)
    REFERENCES `manics`.`comics` (`comic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manics`.`mangas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manics`.`mangas` (
  `manga_id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NULL,
  `anio_publicacion` INT NULL,
  `capitulos_disponibles` INT NULL,
  `categoria_id` INT NULL,
  PRIMARY KEY (`manga_id`),
  INDEX `fk_categoria_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_manga_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `manics`.`categorias` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manics`.`likes_manga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manics`.`likes_manga` (
  `user_id` INT NOT NULL,
  `manga_id` INT NOT NULL,
  `fecha_agregado` VARCHAR(45) NULL,
  INDEX `fk_manga_idx` (`manga_id` ASC) VISIBLE,
  CONSTRAINT `fk_likes_manga`
    FOREIGN KEY (`manga_id`)
    REFERENCES `manics`.`mangas` (`manga_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manics`.`ver_luego_mangas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manics`.`ver_luego_mangas` (
  `user_id` INT NOT NULL,
  `manga_id` INT NOT NULL,
  INDEX `fk_manga_idx` (`manga_id` ASC) VISIBLE,
  CONSTRAINT `fk_verluego_manga`
    FOREIGN KEY (`manga_id`)
    REFERENCES `manics`.`mangas` (`manga_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manics`.`comics_capitulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manics`.`comics_capitulos` (
  `capitulo_id` INT NOT NULL,
  `comic_id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `fecha_publicacion` VARCHAR(45) NULL,
  `total_paginas` VARCHAR(45) NULL,
  INDEX `fk_comic_idx` (`comic_id` ASC) VISIBLE,
  PRIMARY KEY (`capitulo_id`, `comic_id`),
  CONSTRAINT `fk_capitulos_comic`
    FOREIGN KEY (`comic_id`)
    REFERENCES `manics`.`comics` (`comic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manics`.`mangas_capitulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manics`.`mangas_capitulos` (
  `capitulo_id` INT NOT NULL,
  `manga_id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `fecha_publicacion` VARCHAR(45) NULL,
  `total_paginas` VARCHAR(45) NULL,
  INDEX `fk_manga_idx` (`manga_id` ASC) VISIBLE,
  PRIMARY KEY (`capitulo_id`, `manga_id`),
  CONSTRAINT `fk_capitulos_manga`
    FOREIGN KEY (`manga_id`)
    REFERENCES `manics`.`mangas` (`manga_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manics`.`comics_capitulos_paginas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manics`.`comics_capitulos_paginas` (
  `pagina_id` INT NOT NULL,
  `capitulo_id` INT NOT NULL,
  `image_url` VARCHAR(130) NULL,
  INDEX `fk_capitulo_idx` (`capitulo_id` ASC) VISIBLE,
  PRIMARY KEY (`pagina_id`, `capitulo_id`),
  CONSTRAINT `fk_pagina_capitulo_comic`
    FOREIGN KEY (`capitulo_id`)
    REFERENCES `manics`.`comics_capitulos` (`capitulo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manics`.`mangas_capitulos_paginas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manics`.`mangas_capitulos_paginas` (
  `pagina_id` INT NOT NULL,
  `capitulo_id` INT NOT NULL,
  `image_url` VARCHAR(130) NULL,
  PRIMARY KEY (`pagina_id`, `capitulo_id`),
  CONSTRAINT `fk_paginas_capitulo_manga`
    FOREIGN KEY (`capitulo_id`)
    REFERENCES `manics`.`mangas_capitulos` (`capitulo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manics`.`comentarios_mangas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manics`.`comentarios_mangas` (
  `comentario_id` INT NOT NULL,
  `user_id` INT NULL,
  `manga_id` INT NULL,
  `contenido` VARCHAR(45) NULL,
  `fecha_publicacion` VARCHAR(45) NULL,
  PRIMARY KEY (`comentario_id`),
  INDEX `fk_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_manga_idx` (`manga_id` ASC) VISIBLE,
  CONSTRAINT `fk_comentario_user_manga`
    FOREIGN KEY (`user_id`)
    REFERENCES `manics`.`usuarios` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_manga`
    FOREIGN KEY (`manga_id`)
    REFERENCES `manics`.`mangas` (`manga_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manics`.`ver_luego_comics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manics`.`ver_luego_comics` (
  `user_id` INT NOT NULL,
  `comic_id` INT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_comic_idx` (`comic_id` ASC) VISIBLE,
  CONSTRAINT `fk_verluego_comic`
    FOREIGN KEY (`comic_id`)
    REFERENCES `manics`.`comics` (`comic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manics`.`likes_comics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manics`.`likes_comics` (
  `user_id` INT NOT NULL,
  `comic_id` INT NULL,
  `fecha_agregado` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_comic_idx` (`comic_id` ASC) VISIBLE,
  CONSTRAINT `fk_likes_comics`
    FOREIGN KEY (`comic_id`)
    REFERENCES `manics`.`comics` (`comic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
